// SYNTHETIC TEST/PREVIEW DATA. This file is never deployed as a static asset.
import { SERVICES } from '../src/catalog.js';
export function fixtureStatus() {
 const now=new Date().toISOString();
 return {type:'snapshot',demo:true,updatedAt:now,history:[{id:'preview-1',serviceId:'openai',from:'operational',to:'degraded',at:now}],services:SERVICES.map(({url,parser,...s},i)=>({...s,componentSupport:parser==='statuspage',components:s.id==='openai'?[{id:'us',name:'United States',status:'operational'},{id:'eu',name:'Europe',status:'degraded'}]:[],sourceType:parser,nextCheckAt:new Date(Date.now()+300000).toISOString(),consecutiveFailures:0,status:i===15?'degraded':parser==='rss'?'unknown':'operational',incidents:i===15?[{title:'Example incident — synthetic preview',body:'This is demonstration data, not a real service incident.'}]:[],note:parser==='rss'?'Update feed only; confirm health on provider page.':undefined,checkedAt:now,lastSuccessAt:now,mode:i%3===0?'webhook':'scheduled',staleAfterMs:720000}))};
}
export function fixtureWeather(){
 const start=Math.floor(Date.now()/3600000)*3600;const times=Array.from({length:120},(_,i)=>start+i*3600);
 return {conditions:{current:{temperature_2m:68,apparent_temperature:67,wind_speed_10m:6,relative_humidity_2m:62,weather_code:2,wind_direction_10m:225,wind_gusts_10m:14,dew_point_2m:55,cloud_cover:40},hourly:{time:times,temperature_2m:times.map((_,i)=>68+5*Math.sin(i/4)),weather_code:times.map((_,i)=>i<3?2:61),wind_speed_10m:times.map(()=>6),precipitation_probability:times.map((_,i)=>i<5?60:10),precipitation:times.map((_,i)=>i<5?.02:0),wind_gusts_10m:times.map(()=>14)},timezone:'America/New_York',fetchedAt:new Date().toISOString(),daily:{time:Array.from({length:5},(_,i)=>start+i*86400),temperature_2m_max:[71,73,69,65,68],temperature_2m_min:[56,58,55,52,54],weather_code:[2,0,3,61,1],precipitation_probability_max:[10,5,20,65,15],sunrise:times.slice(0,5).map((_,i)=>start+i*86400),sunset:times.slice(0,5).map((_,i)=>start+12*3600+i*86400)}},alerts:{available:true,items:[]},models:[{id:'ecmwf_aifs025_single',name:'ECMWF AIFS',kind:'AI',available:true,fetchedAt:new Date().toISOString(),hourly:{time:times,temperature_2m:times.map((_,i)=>62+8*Math.sin(i/4)),wind_speed_10m:times.map(()=>6)}},{id:'ncep_aigfs025',name:'NOAA AIGFS',kind:'AI',available:true,fetchedAt:new Date().toISOString(),hourly:{time:times,temperature_2m:times.map((_,i)=>63+7*Math.sin((i+1)/4)),wind_speed_10m:times.map(()=>7)}}]};
}

export function fixtureNetworkWatch(){
 const event={id:'demo-outage',type:'Internet outage',description:'Synthetic ISP disruption — preview only',asns:[65001],countries:['US'],state:'Ongoing',start:new Date().toISOString()};
 const events=Array.from({length:13},(_,i)=>({...event,id:`demo-${i}`,description:`Synthetic ISP disruption ${i+1} — preview only`}));
 return {names:{25710:'Example network AS25710',32145:'Example network AS32145',402280:'Example network AS402280',65001:'Example downstream'},checkedAt:new Date().toISOString(),radarConfigured:true,networks:[25710,32145,402280].map(asn=>({asn,name:`Example network AS${asn}`,routingAvailable:true,announced:true,routingAt:new Date().toISOString(),neighboursAvailable:true,downstream:[65001],upstream:[65002],events:[event],eventsAvailable:true,limited:false})),downstream:{available:true,limited:false,events:events.map(event=>({...event,via:[{parent:25710,asn:65001}]}))},northAmerica:{available:true,limited:false,events},feeds:[],window:'7 days'};
}
